matrix:
  include:
  - os: osx
    osx_image: xcode12.2
    language: node_js
    node_js: '12'
    env: DISTRIBUTION=mac
  - os: linux
    dist: bionic
    language: node_js
    node_js: '12'
    env: DISTRIBUTION=snap
    addons:
      snaps:
      - name: snapcraft
        confinement: classic

branches:
  only:
  - master

install:
  - ls -lah

before_script:
- |
  if [[ "$DISTRIBUTION" == "mac" ]]; then
    echo $CERTIFICATE_MAC | base64 --decode > certificate.p12;
    security create-keychain -p travis build.keychain;
    security default-keychain -s build.keychain;
    security unlock-keychain -p travis build.keychain;
    security set-keychain-settings build.keychain;
    security list-keychains -d user -s build.keychain;
    security import certificate.p12 -k build.keychain -P $CERTIFICATE_MAC_PASSWORD -T /usr/bin/codesign -T /usr/bin/productbuild 2>&1 >/dev/null;
    security set-key-partition-list -S apple-tool:,apple: -s -k travis build.keychain 2>&1 >/dev/null;
    rm certificate.p12;
    security find-identity -v
  elif [[ "$DISTRIBUTION" == "snap" ]]; then
    echo "$SNAP_TOKEN" | snapcraft login --with -;
  fi

script:
- npm run publish
