matrix:
  include:
  - os: osx
    osx_image: xcode11.5
    language: node_js
    node_js: '12'

script:
- npm run release

#deploy:
#  edge: true
#  provider: gcs
#  local-dir: dist
#  on:
#    branch: master
