image: Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  DISTRIBUTION: win

install:
  - ps: Install-Product node 12 x64
  - npm ci

build_script:
  - npm run publish

test: off
