image: Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  DISTRIBUTION: win

install:
  - ps: Install-Product node 12 x64
  - npm ci

before_build:
  - ps: >-
      if (Test-Path Env:\CERTIFICATE_WIN) {
        $workingDirectory = Convert-Path (Resolve-Path -path ".")
        $filename = "$workingDirectory\resources\certificate.pfx"
        $bytes = [Convert]::FromBase64String($env:CERTIFICATE_WIN)
        [IO.File]::WriteAllBytes($filename, $bytes)
      }

build_script:
  - npm run publish

test: off
