image: Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  DISTRIBUTION: win
  DISTRIBUTION: appx

install:
  - ps: Install-Product node 14 x64
  - set NODE_ENV=ci
  - npm config set @coinspace:registry https://npm.pkg.github.com
  - npm config set "//npm.pkg.github.com/:_authToken" ${NPM_READ_TOKEN}
  - npm ci

before_build:
  - ps: >-
      if (Test-Path Env:\CERTIFICATE_WIN) {
        $workingDirectory = Convert-Path (Resolve-Path -path ".")
        $filename = "$workingDirectory\resources\certificate.pfx"
        $bytes = [Convert]::FromBase64String($env:CERTIFICATE_WIN)
        [IO.File]::WriteAllBytes($filename, $bytes)
      }
  - ps: $Env:GOOGLE_CLOUD_PRIVATE_KEY=$Env:GOOGLE_CLOUD_PRIVATE_KEY.replace("\n","`n")
  - ps: $Env:DEBUG="electron-windows-store"

build_script:
  - ps: |
      if ($true)
      {
        npm info
        npm version
        npm run publish
        Write-Host "Success"
      }

test: off
